[package]
name = "tiktoken"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "tiktoken"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.33.0"
tiktoken-rs = "0.5.9"
